### ISSUE TITLE
Also store source somehow in links

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe-traph#15]
It could enable us to read the whole find sequentially when aggregating links rather than hopping through it very fast. But it'll double writing cost, so there's that...

**Comment by Yomguithereal** [comment]
We can also store the source only once by differentiating blocks: first block has meta & source + cached list length and the second is the regular list item block.

**Comment by Yomguithereal** [comment]
It should also be noted that this is only useful when scanning the whole graph. It can be slower if only a restricted subset is required.

**Comment by boogheta** [comment]
breaking version

**Comment by boogheta** [comment]
cf #24
