### ISSUE TITLE
Add pagination capabilities to get_webentity_pages

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe-traph#21]
It should be possible by only taking a token as argument pointing toward the last seen block in the trie.

**Comment by boogheta** [comment]
- [x] éditer webentity_dfs_iter pour reprendre un dfs à partir d'un point de l'arbre et continuer en remontant jusqu'au préfixe d'origine
- [x] renvoyer un token de pagination (si il en reste) : index du préfixe et bloc mémoire du noeud
- [x] changer l'api : ajouter le nombre de pages, prévoir de recevoir un token de suite

**Comment by boogheta** [comment]
cf https://github.com/medialab/hyphe/issues/293

**Comment by Yomguithereal** [comment]
https://www.geeksforgeeks.org/inorder-non-threaded-binary-tree-traversal-without-recursion-or-stack/
