### ISSUE TITLE
get_webentity_child_webentities takes forever on big entities

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-traph#22]
We should try to find a way to make these calls faster...

**Comment by Yomguithereal** [comment]
Without caching or max_depth tricks I don't really see how. This query has the same complexity as getting every page of a webentity.

**Comment by boogheta** [comment]
Could we try to add some kind of flag on the tree branches announcing whether WE prefixes exist down the path ? Not sure it would be easy to maintain, but it feels like whenever adding or removing a new WE prefix it would only require to reclimb the tree to the top which shouldn't be too heavy

**Comment by boogheta** [comment]
- [ ] quand on ajoute un prefixe d'une webentité, on flag sur le chemin en descendant les noeuds qui sont des webentités
- [ ] quand on retire un préfixe, c'est compliqué : soit on a une opération lourde pour aller revérifier, soit on fait rien, et ces cas créeront des ralentissement mais suffisamment rares pour que pas grave
- [ ] quand on cherche les entités filles on suit que les noeuds flaggés

**Comment by Yomguithereal** [comment]
What if we insert `com|twitter|yomgui` before `com|twitter`?
