### ISSUE TITLE
Should be possible to use 'c' type rather than 'B'

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe-traph#6]

**Comment by boogheta** [comment]
sounds obvious!

**Comment by Yomguithereal** [comment]
Nia nia nia. C'est juste que ça m'éviterait d'avoir à utiliser `ord` et `chr` pour convertir l'ascii en octets mais comme après le vecteur va stocker des données disparates et que je pourrais pas passer sur un bytearray pour optimiser la RAM je suis pas certain que ce soit utile :P
